-- AlterTable
ALTER TABLE "transactions" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "transacted_at" SET DATA TYPE TIMESTAMPTZ(6);
