/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedAuthRouteImport } from './routes/(authed)/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicConfigIndexRouteImport } from './routes/(public)/config/index'
import { Route as ApiE2eFixturesRouteImport } from './routes/api/e2e/fixtures'
import { Route as ApiE2eSeedRouteImport } from './routes/api/e2e/seed'
import { Route as authedAuthE2eIndexRouteImport } from './routes/(authed)/_auth/e2e/index'
import { Route as authedAuthFinancesindexIndexRouteImport } from './routes/(authed)/_auth/finances/(index)/index'
import { Route as authedAuthFinancesScheduledIdIndexRouteImport } from './routes/(authed)/_auth/finances/scheduled/$id/index'
import { Route as authedAuthFinancesScheduledindexIndexRouteImport } from './routes/(authed)/_auth/finances/scheduled/(index)/index'
import { Route as authedAuthFinancesScheduledArchivedIndexRouteImport } from './routes/(authed)/_auth/finances/scheduled/archived/index'
import { Route as authedAuthFinancesScheduledNewIndexRouteImport } from './routes/(authed)/_auth/finances/scheduled/new/index'
import { Route as authedAuthFinancesTransactionsIdIndexRouteImport } from './routes/(authed)/_auth/finances/transactions/$id/index'
import { Route as authedAuthFinancesTransactionsindexIndexRouteImport } from './routes/(authed)/_auth/finances/transactions/(index)/index'
import { Route as authedAuthFinancesTransactionsNewIndexRouteImport } from './routes/(authed)/_auth/finances/transactions/new/index'

const authedAuthRoute = authedAuthRouteImport.update({
  id: '/(authed)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicConfigIndexRoute = publicConfigIndexRouteImport.update({
  id: '/(public)/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eFixturesRoute = ApiE2eFixturesRouteImport.update({
  id: '/api/e2e/fixtures',
  path: '/api/e2e/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eSeedRoute = ApiE2eSeedRouteImport.update({
  id: '/api/e2e/seed',
  path: '/api/e2e/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const authedAuthE2eIndexRoute = authedAuthE2eIndexRouteImport.update({
  id: '/e2e/',
  path: '/e2e/',
  getParentRoute: () => authedAuthRoute,
} as any)
const authedAuthFinancesindexIndexRoute =
  authedAuthFinancesindexIndexRouteImport.update({
    id: '/finances/(index)/',
    path: '/finances/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesScheduledIdIndexRoute =
  authedAuthFinancesScheduledIdIndexRouteImport.update({
    id: '/finances/scheduled/$id/',
    path: '/finances/scheduled/$id/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesScheduledindexIndexRoute =
  authedAuthFinancesScheduledindexIndexRouteImport.update({
    id: '/finances/scheduled/(index)/',
    path: '/finances/scheduled/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesScheduledArchivedIndexRoute =
  authedAuthFinancesScheduledArchivedIndexRouteImport.update({
    id: '/finances/scheduled/archived/',
    path: '/finances/scheduled/archived/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesScheduledNewIndexRoute =
  authedAuthFinancesScheduledNewIndexRouteImport.update({
    id: '/finances/scheduled/new/',
    path: '/finances/scheduled/new/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesTransactionsIdIndexRoute =
  authedAuthFinancesTransactionsIdIndexRouteImport.update({
    id: '/finances/transactions/$id/',
    path: '/finances/transactions/$id/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesTransactionsindexIndexRoute =
  authedAuthFinancesTransactionsindexIndexRouteImport.update({
    id: '/finances/transactions/(index)/',
    path: '/finances/transactions/',
    getParentRoute: () => authedAuthRoute,
  } as any)
const authedAuthFinancesTransactionsNewIndexRoute =
  authedAuthFinancesTransactionsNewIndexRouteImport.update({
    id: '/finances/transactions/new/',
    path: '/finances/transactions/new/',
    getParentRoute: () => authedAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/api/e2e/fixtures': typeof ApiE2eFixturesRoute
  '/api/e2e/seed': typeof ApiE2eSeedRoute
  '/config/': typeof publicConfigIndexRoute
  '/e2e/': typeof authedAuthE2eIndexRoute
  '/finances/': typeof authedAuthFinancesindexIndexRoute
  '/finances/scheduled/$id/': typeof authedAuthFinancesScheduledIdIndexRoute
  '/finances/scheduled/': typeof authedAuthFinancesScheduledindexIndexRoute
  '/finances/scheduled/archived/': typeof authedAuthFinancesScheduledArchivedIndexRoute
  '/finances/scheduled/new/': typeof authedAuthFinancesScheduledNewIndexRoute
  '/finances/transactions/$id/': typeof authedAuthFinancesTransactionsIdIndexRoute
  '/finances/transactions/': typeof authedAuthFinancesTransactionsindexIndexRoute
  '/finances/transactions/new/': typeof authedAuthFinancesTransactionsNewIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/api/e2e/fixtures': typeof ApiE2eFixturesRoute
  '/api/e2e/seed': typeof ApiE2eSeedRoute
  '/config': typeof publicConfigIndexRoute
  '/e2e': typeof authedAuthE2eIndexRoute
  '/finances': typeof authedAuthFinancesindexIndexRoute
  '/finances/scheduled/$id': typeof authedAuthFinancesScheduledIdIndexRoute
  '/finances/scheduled': typeof authedAuthFinancesScheduledindexIndexRoute
  '/finances/scheduled/archived': typeof authedAuthFinancesScheduledArchivedIndexRoute
  '/finances/scheduled/new': typeof authedAuthFinancesScheduledNewIndexRoute
  '/finances/transactions/$id': typeof authedAuthFinancesTransactionsIdIndexRoute
  '/finances/transactions': typeof authedAuthFinancesTransactionsindexIndexRoute
  '/finances/transactions/new': typeof authedAuthFinancesTransactionsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authed)/_auth': typeof authedAuthRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/api/e2e/fixtures': typeof ApiE2eFixturesRoute
  '/api/e2e/seed': typeof ApiE2eSeedRoute
  '/(public)/config/': typeof publicConfigIndexRoute
  '/(authed)/_auth/e2e/': typeof authedAuthE2eIndexRoute
  '/(authed)/_auth/finances/(index)/': typeof authedAuthFinancesindexIndexRoute
  '/(authed)/_auth/finances/scheduled/$id/': typeof authedAuthFinancesScheduledIdIndexRoute
  '/(authed)/_auth/finances/scheduled/(index)/': typeof authedAuthFinancesScheduledindexIndexRoute
  '/(authed)/_auth/finances/scheduled/archived/': typeof authedAuthFinancesScheduledArchivedIndexRoute
  '/(authed)/_auth/finances/scheduled/new/': typeof authedAuthFinancesScheduledNewIndexRoute
  '/(authed)/_auth/finances/transactions/$id/': typeof authedAuthFinancesTransactionsIdIndexRoute
  '/(authed)/_auth/finances/transactions/(index)/': typeof authedAuthFinancesTransactionsindexIndexRoute
  '/(authed)/_auth/finances/transactions/new/': typeof authedAuthFinancesTransactionsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/api/e2e/fixtures'
    | '/api/e2e/seed'
    | '/config/'
    | '/e2e/'
    | '/finances/'
    | '/finances/scheduled/$id/'
    | '/finances/scheduled/'
    | '/finances/scheduled/archived/'
    | '/finances/scheduled/new/'
    | '/finances/transactions/$id/'
    | '/finances/transactions/'
    | '/finances/transactions/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/e2e/fixtures'
    | '/api/e2e/seed'
    | '/config'
    | '/e2e'
    | '/finances'
    | '/finances/scheduled/$id'
    | '/finances/scheduled'
    | '/finances/scheduled/archived'
    | '/finances/scheduled/new'
    | '/finances/transactions/$id'
    | '/finances/transactions'
    | '/finances/transactions/new'
  id:
    | '__root__'
    | '/(authed)/_auth'
    | '/(public)/login'
    | '/(public)/'
    | '/api/e2e/fixtures'
    | '/api/e2e/seed'
    | '/(public)/config/'
    | '/(authed)/_auth/e2e/'
    | '/(authed)/_auth/finances/(index)/'
    | '/(authed)/_auth/finances/scheduled/$id/'
    | '/(authed)/_auth/finances/scheduled/(index)/'
    | '/(authed)/_auth/finances/scheduled/archived/'
    | '/(authed)/_auth/finances/scheduled/new/'
    | '/(authed)/_auth/finances/transactions/$id/'
    | '/(authed)/_auth/finances/transactions/(index)/'
    | '/(authed)/_auth/finances/transactions/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedAuthRoute: typeof authedAuthRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiE2eFixturesRoute: typeof ApiE2eFixturesRoute
  ApiE2eSeedRoute: typeof ApiE2eSeedRoute
  publicConfigIndexRoute: typeof publicConfigIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)/_auth': {
      id: '/(authed)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/config/': {
      id: '/(public)/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof publicConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/fixtures': {
      id: '/api/e2e/fixtures'
      path: '/api/e2e/fixtures'
      fullPath: '/api/e2e/fixtures'
      preLoaderRoute: typeof ApiE2eFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/seed': {
      id: '/api/e2e/seed'
      path: '/api/e2e/seed'
      fullPath: '/api/e2e/seed'
      preLoaderRoute: typeof ApiE2eSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/_auth/e2e/': {
      id: '/(authed)/_auth/e2e/'
      path: '/e2e'
      fullPath: '/e2e/'
      preLoaderRoute: typeof authedAuthE2eIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/(index)/': {
      id: '/(authed)/_auth/finances/(index)/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof authedAuthFinancesindexIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/scheduled/$id/': {
      id: '/(authed)/_auth/finances/scheduled/$id/'
      path: '/finances/scheduled/$id'
      fullPath: '/finances/scheduled/$id/'
      preLoaderRoute: typeof authedAuthFinancesScheduledIdIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/scheduled/(index)/': {
      id: '/(authed)/_auth/finances/scheduled/(index)/'
      path: '/finances/scheduled'
      fullPath: '/finances/scheduled/'
      preLoaderRoute: typeof authedAuthFinancesScheduledindexIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/scheduled/archived/': {
      id: '/(authed)/_auth/finances/scheduled/archived/'
      path: '/finances/scheduled/archived'
      fullPath: '/finances/scheduled/archived/'
      preLoaderRoute: typeof authedAuthFinancesScheduledArchivedIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/scheduled/new/': {
      id: '/(authed)/_auth/finances/scheduled/new/'
      path: '/finances/scheduled/new'
      fullPath: '/finances/scheduled/new/'
      preLoaderRoute: typeof authedAuthFinancesScheduledNewIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/transactions/$id/': {
      id: '/(authed)/_auth/finances/transactions/$id/'
      path: '/finances/transactions/$id'
      fullPath: '/finances/transactions/$id/'
      preLoaderRoute: typeof authedAuthFinancesTransactionsIdIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/transactions/(index)/': {
      id: '/(authed)/_auth/finances/transactions/(index)/'
      path: '/finances/transactions'
      fullPath: '/finances/transactions/'
      preLoaderRoute: typeof authedAuthFinancesTransactionsindexIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
    '/(authed)/_auth/finances/transactions/new/': {
      id: '/(authed)/_auth/finances/transactions/new/'
      path: '/finances/transactions/new'
      fullPath: '/finances/transactions/new/'
      preLoaderRoute: typeof authedAuthFinancesTransactionsNewIndexRouteImport
      parentRoute: typeof authedAuthRoute
    }
  }
}

interface authedAuthRouteChildren {
  authedAuthE2eIndexRoute: typeof authedAuthE2eIndexRoute
  authedAuthFinancesindexIndexRoute: typeof authedAuthFinancesindexIndexRoute
  authedAuthFinancesScheduledIdIndexRoute: typeof authedAuthFinancesScheduledIdIndexRoute
  authedAuthFinancesScheduledindexIndexRoute: typeof authedAuthFinancesScheduledindexIndexRoute
  authedAuthFinancesScheduledArchivedIndexRoute: typeof authedAuthFinancesScheduledArchivedIndexRoute
  authedAuthFinancesScheduledNewIndexRoute: typeof authedAuthFinancesScheduledNewIndexRoute
  authedAuthFinancesTransactionsIdIndexRoute: typeof authedAuthFinancesTransactionsIdIndexRoute
  authedAuthFinancesTransactionsindexIndexRoute: typeof authedAuthFinancesTransactionsindexIndexRoute
  authedAuthFinancesTransactionsNewIndexRoute: typeof authedAuthFinancesTransactionsNewIndexRoute
}

const authedAuthRouteChildren: authedAuthRouteChildren = {
  authedAuthE2eIndexRoute: authedAuthE2eIndexRoute,
  authedAuthFinancesindexIndexRoute: authedAuthFinancesindexIndexRoute,
  authedAuthFinancesScheduledIdIndexRoute:
    authedAuthFinancesScheduledIdIndexRoute,
  authedAuthFinancesScheduledindexIndexRoute:
    authedAuthFinancesScheduledindexIndexRoute,
  authedAuthFinancesScheduledArchivedIndexRoute:
    authedAuthFinancesScheduledArchivedIndexRoute,
  authedAuthFinancesScheduledNewIndexRoute:
    authedAuthFinancesScheduledNewIndexRoute,
  authedAuthFinancesTransactionsIdIndexRoute:
    authedAuthFinancesTransactionsIdIndexRoute,
  authedAuthFinancesTransactionsindexIndexRoute:
    authedAuthFinancesTransactionsindexIndexRoute,
  authedAuthFinancesTransactionsNewIndexRoute:
    authedAuthFinancesTransactionsNewIndexRoute,
}

const authedAuthRouteWithChildren = authedAuthRoute._addFileChildren(
  authedAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedAuthRoute: authedAuthRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
  ApiE2eFixturesRoute: ApiE2eFixturesRoute,
  ApiE2eSeedRoute: ApiE2eSeedRoute,
  publicConfigIndexRoute: publicConfigIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
