/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as indexIndexRouteImport } from './routes/(index)/index'
import { Route as AuthFinancesIndexRouteImport } from './routes/_auth/finances/index'
import { Route as indexConfigIndexRouteImport } from './routes/(index)/config/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/(index)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFinancesIndexRoute = AuthFinancesIndexRouteImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => AuthRoute,
} as any)
const indexConfigIndexRoute = indexConfigIndexRouteImport.update({
  id: '/(index)/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexIndexRoute
  '/login': typeof LoginRoute
  '/config/': typeof indexConfigIndexRoute
  '/finances/': typeof AuthFinancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexIndexRoute
  '/login': typeof LoginRoute
  '/config': typeof indexConfigIndexRoute
  '/finances': typeof AuthFinancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/(index)/': typeof indexIndexRoute
  '/(index)/config/': typeof indexConfigIndexRoute
  '/_auth/finances/': typeof AuthFinancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/config/' | '/finances/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/config' | '/finances'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/(index)/'
    | '/(index)/config/'
    | '/_auth/finances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  indexIndexRoute: typeof indexIndexRoute
  indexConfigIndexRoute: typeof indexConfigIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(index)/': {
      id: '/(index)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/finances/': {
      id: '/_auth/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthFinancesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(index)/config/': {
      id: '/(index)/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof indexConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthFinancesIndexRoute: typeof AuthFinancesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFinancesIndexRoute: AuthFinancesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  indexIndexRoute: indexIndexRoute,
  indexConfigIndexRoute: indexConfigIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
